# Generated by Django 3.1.7 on 2021-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210314_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('APPETIZERS', 'Appetizers'), ('SOUP', 'Soup'), ('FRIED_RICE', 'Fried Rice')], default=('OTHER', 'Other'), max_length=30),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
